# Use the official PostgreSQL image
FROM postgres:latest
# Set the environment variables for PostgreSQL, feel free to change them
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=postgrespassword
ENV POSTGRES_DB=postgres
# Expose the default PostgreSQL port
EXPOSE 5434
# Command to run the PostgreSQL server
CMD ["postgres"]