#!/usr/bin/env python3
"""
bundle_docs.py <src_dir> <out_cpp>

Walks src_dir (recursively) and emits a single C++ file that exposes every
file as a `static const unsigned char[]` plus a `docs_assets()` registry
mapping the relative path → {data, size, mime}. Used at build time to
embed the Doxygen output into the engine binary.
"""

from __future__ import annotations
import os
import sys
from pathlib import Path

MIME_BY_EXT = {
    ".html": "text/html; charset=utf-8",
    ".htm":  "text/html; charset=utf-8",
    ".css":  "text/css",
    ".js":   "application/javascript",
    ".json": "application/json",
    ".map":  "application/json",
    ".md":   "text/markdown",
    ".txt":  "text/plain",
    ".png":  "image/png",
    ".jpg":  "image/jpeg",
    ".jpeg": "image/jpeg",
    ".svg":  "image/svg+xml",
    ".gif":  "image/gif",
    ".ico":  "image/x-icon",
    ".woff": "font/woff",
    ".woff2": "font/woff2",
    ".ttf":  "font/ttf",
    ".md5":  "text/plain",
    ".xml":  "application/xml",
    ".yaml": "text/yaml",
    ".yml":  "text/yaml",
}


def mime_for(name: str) -> str:
    ext = os.path.splitext(name)[1].lower()
    return MIME_BY_EXT.get(ext, "application/octet-stream")


def safe_ident(rel: str) -> str:
    return "asset_" + "".join(c if c.isalnum() else "_" for c in rel)


def emit_array(out, ident: str, data: bytes) -> None:
    out.write(f"static const unsigned char {ident}[] = {{\n")
    line = []
    for i, b in enumerate(data):
        line.append(f"0x{b:02x}")
        if (i + 1) % 16 == 0:
            out.write("  " + ",".join(line) + ",\n")
            line.clear()
    if line:
        out.write("  " + ",".join(line) + ",\n")
    # Empty file edge case: produce a 1-byte placeholder so size != 0 weirdness
    # never bites; we still report the original length below.
    if not data:
        out.write("  0x00\n")
    out.write("};\n")


def main() -> int:
    if len(sys.argv) != 3:
        print("usage: bundle_docs.py <src_dir> <out_cpp>", file=sys.stderr)
        return 2

    src_dir = Path(sys.argv[1]).resolve()
    out_path = Path(sys.argv[2]).resolve()
    out_path.parent.mkdir(parents=True, exist_ok=True)

    if not src_dir.is_dir():
        print(f"bundle_docs: {src_dir} is not a directory", file=sys.stderr)
        return 1

    assets: list[tuple[str, str, bytes, str]] = []
    for p in sorted(src_dir.rglob("*")):
        if not p.is_file():
            continue
        rel = p.relative_to(src_dir).as_posix()
        ident = safe_ident(rel)
        data = p.read_bytes()
        assets.append((rel, ident, data, mime_for(rel)))

    total = sum(len(d) for _, _, d, _ in assets)
    print(f"bundle_docs: bundling {len(assets)} files, {total} bytes from {src_dir}",
          file=sys.stderr)

    with out_path.open("w") as out:
        out.write("// Auto-generated by scripts/bundle_docs.py — DO NOT EDIT.\n")
        out.write('#include "server/docs_bundle.hpp"\n')
        out.write("#include <unordered_map>\n\n")
        out.write("namespace TradingSystem {\n\n")

        for rel, ident, data, _mime in assets:
            real_size = len(data)
            emit_array(out, ident, data)
            # Record real size so we don't serve the placeholder padding byte.
            out.write(f"static const std::size_t {ident}_len = {real_size};\n\n")

        out.write("const std::unordered_map<std::string, DocsAsset>& docs_assets() {\n")
        out.write("    static const std::unordered_map<std::string, DocsAsset> kMap = {\n")
        for rel, ident, _data, mime in assets:
            esc = rel.replace("\\", "\\\\").replace('"', '\\"')
            out.write(f'        {{ "{esc}", {{{ident}, {ident}_len, "{mime}"}} }},\n')
        out.write("    };\n    return kMap;\n}\n\n")
        out.write("}  // namespace TradingSystem\n")

    return 0


if __name__ == "__main__":
    sys.exit(main())
